services:
  _defaults:
    public: true

  mporderflag.controller.admin.product_stock_service:
    class: MpSoft\MpOrderFlag\Controllers\Admin\MpOrderFlagController
    arguments:
      - "@prestashop.core.admin.data_provider.product_interface"
      - "@prestashop.adapter.legacy.context"
    tags:
      - { name: controller.service_arguments }
