services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  MpSoft\MpOrderFlag\Controllers\Admin\MpOrderFlagController:
    class: MpSoft\MpOrderFlag\Controllers\Admin\MpOrderFlagController
    public: true
    arguments:
      $legacyContext: "@prestashop.adapter.legacy.context"
    tags:
      - { name: "controller.service_arguments" }
